{{- if and (.Values.externalSecrets.enabled | default false) .Values.helicone.aiGateway.enabled }}
# TODO It might be better to manage this in the ai-gateway-cloud chart
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helicone-ai-gateway-sidecar-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "30s" | quote }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: helicone-ai-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: openai_api_key
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/ai-gateway
        property: openai_api_key
    - secretKey: anthropic_api_key
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/ai-gateway
        property: anthropic_api_key
    - secretKey: gemini_api_key
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/ai-gateway
        property: gemini_api_key
    - secretKey: helicone_api_key
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/ai-gateway
        property: helicone_api_key
{{- end }} 