################################################################################
#
#                            HELICONE ARGOCD
#
################################################################################

argocd:
  enabled: true
  createProject: true
  namespace: helicone-argocd
  project: helicone
  source:
    repoURL: "https://github.com/Helicone/helicone-helm-v3.git"
    targetRevision: main
    path: charts/helicone-core
    helm:
      valueFiles:
        - values.yaml
      parameters: []

  destination:
    server: https://kubernetes.default.svc
    namespace: helicone

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 3

argo-cd:
  enabled: true
  global:
    domain: argocd.helicone.ai

  crds:
    install: true
    keep: true

  # Server configuration
  server:
    service:
      type: ClusterIP
      servicePortHttp: 80
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - argocd.helicone.ai
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.helicone.ai
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/server-snippet: |
          grpc_read_timeout 300;
          grpc_send_timeout 300;

  # Disable Dex for simplicity (use built-in admin user)
  dex:
    enabled: false

  # Configs
  configs:
    params:
      server.insecure: true # TODO Set this to false in production
